name: diario as - selenium
# run-name: selenium - ${{ inputs.os }} - ${{ inputs.browser }}
run-name: selenium - ubuntu-latest - ${{ inputs.browser }}

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Elige el navegador
        required: true
        options:
          - chrome
          - safari
          - firefox
      allure:
        type: boolean
        description: Publicar en Allure
        default: true
      extent:
        type: boolean
        description: Generar reporte Extent
        default: true
      pdf:
        type: boolean
        description: Generar PDF
        default: true
      recorder:
        type: boolean
        description: Grabar la ejecución
        default: true

jobs:
  selenium:
    # runs-on: ${{ github.event.inputs.os }}
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate artifact for Allure Reports
        uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.allure == 'true' }}
        with:
          name: report_allure
          path: ./allure-results

  allure:
    needs: selenium
    if: ${{ github.event.inputs.allure == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: report_allure
          path: ./allure-results

      - run: sudo apt-get install tree
      - run: cd
      - run: tree



      - name: Get AllureReports history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          # path: ./reports/chrome-desktop/allure


      - run: cd
      - run: tree
      
      - name: Get AllureReports results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: ./gh-pages/reports/chrome-desktop/allure/allure-history
          keep_reports: 10

      - run: cd
      - run: tree
